version: '3.8'
services:
  app:
    image: ghcr.io/alexdjachenko/phpresticadmin:latest
    ports:
      - "8080:80"
    volumes:
      - phpresticadmin_data:/var/www/data
    deploy:
      replicas: 1

volumes:
  phpresticadmin_data:
